name: Build Web & Deploy to GH
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: '4.0.7'
          actions-cache-folder: 'emsdk-cache'

      - name: Install and Build # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          embuilder build zlib --lto
          embuilder build sdl3 --lto
          cmake --preset emsdk
          cmake --build --preset emsdk

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/emsdk/bin # The folder the action should deploy.
